---

- name: install dependencies
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
     - jq
     - python3
     - curl

- name: install retry
  dnf:
    name: "{{ aws_ec2_environment_rpm_retry }}"
    disable_gpg_check: yes
    state: present

- name: copy ec2-environment script
  ansible.builtin.copy:
    src: files/ec2-environment
    dest: /usr/bin/ec2-environment
    mode: '0755'
    owner: root
    group: root

- name: create ec2-environment service
  template: src=templates/ec2-environment.service.j2 dest=/usr/lib/systemd/system/ec2-environment.service owner=root group=root mode=0644
  notify:
    - aws_ec2_environment daemon-reload

- name: enable ec2-environment on boot
  service: name=ec2-environment enabled=yes
