---
- name: install dependencies
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - jq
      - python3
      - curl
      - retry
      - ipcalc

- name: copy ec2-environment script
  ansible.builtin.copy:
    src: files/ec2-environment
    dest: /usr/bin/ec2-environment
    mode: 0755
    owner: root
    group: root

- name: create directory for ec2-environment systemd drop-ins
  ansible.builtin.file:
    path: /etc/systemd/system/ec2-environment.service.d
    owner: root
    group: root
    state: directory
    mode: 0755

- name: create ec2-environment service
  ansible.builtin.template:
    src: templates/ec2-environment.service.j2
    dest: /usr/lib/systemd/system/ec2-environment.service
    owner: root
    group: root
    mode: 0644
  notify:
    - aws_environment daemon-reload

- name: enable ec2-environment on boot
  ansible.builtin.service:
    name: ec2-environment
    enabled: true
